export const IMAGES = {
  splashLogo: require('../../assets/splashImage.jpg'),
  onboardingImage1: require('../../assets/Mask_Group_7.png'),
  onboardingImage2: require('../../assets/Usability_testing-pana.png'),
  onboardingImage3: require('../../assets/Group_4077.png'),
  onboardingImage4: require('../../assets/Product_quality-pana.png'),
  objectsImage: require('../../assets/Group_4043.png'),
  sirasizLogo: require('../../assets/more.png'),
  phoneIconBlue: require('../../assets/Group_1924.png'),
  userLogo: require('../../assets/Path_10569.png'),
  phoneIconGray: require('../../assets/Group_192.png'),
  crossIcon: require('../../assets/Path_10601.png'),
  profileLogo: require('../../assets/Path_10594.png'),
  bellIcon: require('../../assets/Path_10595.png'),
  appointmentIcon: require('../../assets/Path_10596.png'),
  termsIcon: require('../../assets/Path_10598.png'),
  privacyPolicyIcon: require('../../assets/Path_10599.png'),
  helpIcon: require('../../assets/Path_10597.png'),
  chevronRight: require('../../assets/Path_11054.png'),
  logoutIcon: require('../../assets/Path_10600.png'),
};
